FROM python:alpine

#RUN mkdir -p /www # Probably not needed
COPY ./www/requirements.txt /www/
WORKDIR /www
RUN pip install -r requirements.txt

COPY ./www /www
#ENV LISTEN_PORT=5000 # Only for Nginx config
#EXPOSE 5000 # not sure if needed

#CMD ["gunicorn", "-w 2", "cloudgpu:app"] # without bind
#CMD ["python", "cloudgpu.py"] # runs Flask server

CMD ["gunicorn", "-w 2", "-b 0.0.0.0:5000", "cloudgpu:app"]